import "dotenv/config";
import express, { type NextFunction, type Request, type Response } from "express";
import cookieParser from "cookie-parser";
import cors from "cors";
import helmet from "helmet";
import swaggerUi from "swagger-ui-express";
import rateLimit from "express-rate-limit";
import multer from "multer";
import sharp from "sharp";
import argon2 from "argon2";
import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { Prisma } from "@prisma/client";
import { ZodError } from "zod";
import { LANGUAGES, ORDER_STATUSES, checkoutSchema, nextOrderStatuses, parseBoolean, phoneSchema, productInputSchema, type Language, type OrderStatus } from "@lumielle/shared";
import { prisma } from "./lib/prisma.js";
import { clearAuthCookie, requireAuth, setAuthCookie, type AuthedRequest } from "./lib/auth.js";
import { fail, ok } from "./lib/http.js";
import { localizedProduct, slugify } from "./lib/product.js";
import { openApi } from "./openapi.js";

const app = express();
const uploadRoot = path.resolve(process.env.UPLOADS_DIR ?? "./uploads");
const allowedOrigins = (process.env.CORS_ORIGINS ?? "http://localhost:3000,http://localhost:5174").split(",");
app.use(helmet({ crossOriginResourcePolicy: false }));
app.use(cors({ origin: (origin, callback) => callback(null, !origin || allowedOrigins.includes(origin)), credentials: true }));
app.use(express.json({ limit: "1mb" })); app.use(cookieParser()); app.use("/uploads", express.static(uploadRoot));
app.get("/api/openapi.json", (_req, res) => res.json(openApi));
app.use("/api-docs", swaggerUi.serve, swaggerUi.setup(openApi, { customSiteTitle: "Lumielle Flowers API Docs" }));
app.use("/api", rateLimit({ windowMs: 60_000, limit: 180, standardHeaders: true, legacyHeaders: false }));
const language = (req: Request): Language => { const value = String(req.query.lang ?? req.headers["accept-language"]?.slice(0, 2) ?? "uz"); return LANGUAGES.includes(value as Language) ? value as Language : "uz"; };
const pageParams = (req: Request) => ({ page: Math.max(1, Number(req.query.page) || 1), limit: Math.min(48, Math.max(1, Number(req.query.limit) || 12)) });
const routeParam = (value: string | string[] | undefined) => Array.isArray(value) ? value[0] : value ?? "";
const productInclude = { images: { orderBy: { sortOrder: "asc" as const } }, category: true };
const serializeProduct = (p: any, lang: Language) => localizedProduct(p, lang);
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 5 * 1024 * 1024, files: 6 }, fileFilter: (_r, file, cb) => cb(null, ["image/jpeg", "image/png", "image/webp"].includes(file.mimetype)) });

app.get("/api/health", (_req, res) => ok(res, { status: "ok" }));
app.get("/api/products", async (req, res, next) => { try {
  const lang = language(req), { page, limit } = pageParams(req);
  const isActive = true;
  const ids = typeof req.query.ids === "string" ? req.query.ids.split(",") : undefined;
  const search = typeof req.query.search === "string" ? req.query.search.trim() : "";
  const where: any = { ...(isActive === undefined ? {} : { isActive }), ...(ids ? { id: { in: ids } } : {}), ...(req.query.category ? { category: { slug: String(req.query.category) } } : {}), ...(req.query.sale === "true" ? { discountPrice: { not: null } } : {}), ...(search ? { OR: [{ titleUz: { contains: search, mode: "insensitive" } }, { titleRu: { contains: search, mode: "insensitive" } }, { titleEn: { contains: search, mode: "insensitive" } }] } : {}) };
  const sort = req.query.sort === "price_asc" ? { price: "asc" } : req.query.sort === "price_desc" ? { price: "desc" } : { createdAt: "desc" };
  const [total, products] = await Promise.all([prisma.product.count({ where }), prisma.product.findMany({ where, include: productInclude, orderBy: sort as any, skip: (page - 1) * limit, take: limit })]);
  ok(res, products.map(p => serializeProduct(p, lang)), 200, { page, limit, total, totalPages: Math.ceil(total / limit) });
} catch (error) { next(error); } });
app.get("/api/products/:slug", async (req, res, next) => { try { const slug = routeParam(req.params.slug); const p = await prisma.product.findFirst({ where: { OR: [{ slug }, { id: slug }] }, include: productInclude }); if (!p) return fail(res, 404, "NOT_FOUND", "Mahsulot topilmadi"); ok(res, serializeProduct(p, language(req))); } catch (e) { next(e); } });
app.get("/api/categories", async (_req, res, next) => { try { ok(res, await prisma.category.findMany({ orderBy: { name: "asc" } })); } catch (e) { next(e); } });
app.get("/api/admin/products", requireAuth("admin"), async (req, res, next) => { try { const { page, limit } = pageParams(req); let isActive: boolean | undefined; try { isActive = parseBoolean(req.query.isActive); } catch { return fail(res, 400, "VALIDATION_ERROR", "isActive noto'g'ri"); } const search = typeof req.query.search === "string" ? req.query.search.trim() : ""; const where: any = { ...(isActive === undefined ? {} : { isActive }), ...(search ? { titleUz: { contains: search, mode: "insensitive" } } : {}) }; const [total, products] = await Promise.all([prisma.product.count({ where }), prisma.product.findMany({ where, include: productInclude, orderBy: { createdAt: "desc" }, skip: (page - 1) * limit, take: limit })]); ok(res, products, 200, { page, limit, total, totalPages: Math.ceil(total / limit) }); } catch (e) { next(e); } });
app.get("/api/admin/products/:id", requireAuth("admin"), async (req, res, next) => { try { const product = await prisma.product.findUnique({ where: { id: routeParam(req.params.id) }, include: productInclude }); if (!product) return fail(res, 404, "NOT_FOUND", "Mahsulot topilmadi"); ok(res, product); } catch (e) { next(e); } });

app.post("/api/auth/request-otp", rateLimit({ windowMs: 60_000, limit: 3 }), async (req, res, next) => { try { const parsed = phoneSchema.safeParse(req.body.phone); if (!parsed.success) return fail(res, 400, "VALIDATION_ERROR", "Telefon noto'g'ri", { phone: "+998XXXXXXXXX kiriting" }); const customer = await prisma.customer.upsert({ where: { phone: parsed.data }, update: {}, create: { phone: parsed.data } }); const recent = await prisma.otpCode.findFirst({ where: { customerId: customer.id, createdAt: { gt: new Date(Date.now() - 60_000) } }, orderBy: { createdAt: "desc" } }); if (recent) return fail(res, 429, "OTP_COOLDOWN", "Kod yaqinda yuborilgan"); const code = process.env.NODE_ENV === "production" ? String(crypto.randomInt(100000, 1000000)) : process.env.OTP_DEV_CODE ?? "123456"; await prisma.otpCode.create({ data: { customerId: customer.id, codeHash: await argon2.hash(code + process.env.OTP_PEPPER), expiresAt: new Date(Date.now() + 5 * 60_000) } }); ok(res, { sent: true, ...(process.env.NODE_ENV !== "production" ? { devCode: code } : {}) }); } catch (e) { next(e); } });
app.post("/api/auth/verify-otp", async (req, res, next) => { try { const phone = phoneSchema.safeParse(req.body.phone); const code = String(req.body.code ?? ""); if (!phone.success || !/^\d{6}$/.test(code)) return fail(res, 400, "VALIDATION_ERROR", "Kod yoki telefon noto'g'ri"); const customer = await prisma.customer.findUnique({ where: { phone: phone.data } }); const otp = customer && await prisma.otpCode.findFirst({ where: { customerId: customer.id }, orderBy: { createdAt: "desc" } }); if (!customer || !otp || otp.expiresAt < new Date()) return fail(res, 400, "OTP_EXPIRED", "Kodning muddati tugagan"); if (otp.attempts >= 5) return fail(res, 429, "OTP_TOO_MANY_ATTEMPTS", "Urinishlar limiti tugadi"); if (!await argon2.verify(otp.codeHash, code + process.env.OTP_PEPPER)) { await prisma.otpCode.update({ where: { id: otp.id }, data: { attempts: { increment: 1 } } }); return fail(res, 400, "OTP_INVALID", "Kod noto'g'ri"); } await prisma.otpCode.delete({ where: { id: otp.id } }); setAuthCookie(res, customer.id, "customer"); ok(res, { id: customer.id, phone: customer.phone, name: customer.name }); } catch (e) { next(e); } });
app.post("/api/auth/logout", (_req, res) => { clearAuthCookie(res, "customer"); ok(res, { loggedOut: true }); });
app.get("/api/me", requireAuth("customer"), async (req: AuthedRequest, res, next) => { try { const c = await prisma.customer.findUnique({ where: { id: req.auth!.id } }); ok(res, c); } catch (e) { next(e); } });
app.patch("/api/me", requireAuth("customer"), async (req: AuthedRequest, res, next) => { try { const name = typeof req.body?.name === "string" ? req.body.name.trim() : ""; if (!name || name.length > 120) return fail(res, 400, "VALIDATION_ERROR", "Ism familiya 1 dan 120 belgigacha bo‘lishi kerak", { name: "Majburiy maydon" }); const customer = await prisma.customer.update({ where: { id: req.auth!.id }, data: { name } }); ok(res, customer); } catch (e) { next(e); } });

app.get("/api/orders", requireAuth("customer"), async (req: AuthedRequest, res, next) => { try { ok(res, await prisma.order.findMany({ where: { customerId: req.auth!.id }, include: { items: true, history: { orderBy: { createdAt: "asc" } } }, orderBy: { createdAt: "desc" } })); } catch (e) { next(e); } });
app.get("/api/orders/:id", requireAuth("customer"), async (req: AuthedRequest, res, next) => { try { const order = await prisma.order.findFirst({ where: { id: routeParam(req.params.id), customerId: req.auth!.id }, include: { items: true, history: { orderBy: { createdAt: "asc" } } } }); if (!order) return fail(res, 404, "NOT_FOUND", "Buyurtma topilmadi"); ok(res, order); } catch (e) { next(e); } });
app.post("/api/orders", requireAuth("customer"), async (req: AuthedRequest, res, next) => { try { const parsed = checkoutSchema.safeParse(req.body); if (!parsed.success) return fail(res, 400, "VALIDATION_ERROR", "Ma'lumotlar noto'g'ri"); const key = req.header("Idempotency-Key"); if (!key) return fail(res, 400, "VALIDATION_ERROR", "Idempotency-Key talab qilinadi"); const existing = await prisma.order.findUnique({ where: { idempotencyKey: key }, include: { items: true } }); if (existing) return ok(res, existing, 200); const ids = parsed.data.items.map(i => i.productId); const products = await prisma.product.findMany({ where: { id: { in: ids }, isActive: true } }); const missing = ids.filter(id => !products.some(p => p.id === id)); if (missing.length) return res.status(409).json({ error: { code: "PRODUCT_UNAVAILABLE", message: "Ba'zi mahsulotlar mavjud emas", productIds: missing } }); const byId = new Map(products.map(p => [p.id, p])); const total = parsed.data.items.reduce((sum, item) => sum + (byId.get(item.productId)!.discountPrice ?? byId.get(item.productId)!.price) * item.quantity, 0);
  const order = await prisma.$transaction(async tx => { const created = await tx.order.create({ data: { customerId: req.auth!.id, customerName: parsed.data.customerName, customerPhone: (await tx.customer.findUniqueOrThrow({ where: { id: req.auth!.id } })).phone, recipientPhone: parsed.data.recipientPhone, address: parsed.data.address, latitude: parsed.data.latitude ?? null, longitude: parsed.data.longitude ?? null, note: parsed.data.note, total, idempotencyKey: key, items: { create: parsed.data.items.map(item => { const p = byId.get(item.productId)!; const unitPrice = p.discountPrice ?? p.price; return { productId: p.id, productTitle: p.titleUz, unitPrice, quantity: item.quantity, lineTotal: unitPrice * item.quantity }; }) }, history: { create: { status: "new" } } }, include: { items: true, history: true } }); return created; }); ok(res, order, 201); } catch (e: any) { if (e.code === "P2002") return fail(res, 409, "CONFLICT", "Takror buyurtma"); next(e); } });

app.post("/api/admin/auth/login", async (req, res, next) => { try { const admin = await prisma.admin.findUnique({ where: { login: String(req.body.login ?? "") } }); if (!admin || !await argon2.verify(admin.passwordHash, String(req.body.password ?? ""))) return fail(res, 401, "UNAUTHORIZED", "Login yoki parol noto'g'ri"); setAuthCookie(res, admin.id, "admin"); ok(res, { id: admin.id, login: admin.login }); } catch (e) { next(e); } });
app.post("/api/admin/auth/logout", (_req, res) => { clearAuthCookie(res, "admin"); ok(res, { loggedOut: true }); });
app.get("/api/admin/dashboard", requireAuth("admin"), async (_req, res, next) => { try { const today = new Date(); today.setUTCHours(19, 0, 0, 0); const [newCount, todayOrders, latest] = await Promise.all([prisma.order.count({ where: { status: "new" } }), prisma.order.aggregate({ where: { createdAt: { gte: today } }, _count: true, _sum: { total: true } }), prisma.order.findMany({ take: 10, orderBy: { createdAt: "desc" } })]); ok(res, { newCount, todayCount: todayOrders._count, todayTotal: todayOrders._sum.total ?? 0, latest }); } catch (e) { next(e); } });
app.get("/api/admin/orders", requireAuth("admin"), async (req, res, next) => { try { const { page, limit } = pageParams(req); const where: any = {}; if (ORDER_STATUSES.includes(req.query.status as OrderStatus)) where.status = req.query.status; if (req.query.search) where.OR = [{ customerPhone: { contains: String(req.query.search) } }, { customerName: { contains: String(req.query.search), mode: "insensitive" } }]; const [total, orders] = await Promise.all([prisma.order.count({ where }), prisma.order.findMany({ where, orderBy: { createdAt: "desc" }, skip: (page - 1) * limit, take: limit })]); ok(res, orders, 200, { page, limit, total, totalPages: Math.ceil(total / limit) }); } catch (e) { next(e); } });
app.get("/api/admin/orders/new-count", requireAuth("admin"), async (_req, res, next) => { try { ok(res, { count: await prisma.order.count({ where: { status: "new" } }) }); } catch (e) { next(e); } });
app.get("/api/admin/orders/:id", requireAuth("admin"), async (req, res, next) => { try { const order = await prisma.order.findUnique({ where: { id: routeParam(req.params.id) }, include: { items: true, history: { orderBy: { createdAt: "asc" } } } }); if (!order) return fail(res, 404, "NOT_FOUND", "Buyurtma topilmadi"); ok(res, order); } catch (e) { next(e); } });
app.patch("/api/admin/orders/:id/status", requireAuth("admin"), async (req, res, next) => { try { const order = await prisma.order.findUnique({ where: { id: routeParam(req.params.id) } }); const status = req.body.status as OrderStatus; if (!order) return fail(res, 404, "NOT_FOUND", "Buyurtma topilmadi"); if (!ORDER_STATUSES.includes(status) || !nextOrderStatuses[order.status].includes(status)) return fail(res, 409, "INVALID_STATUS_TRANSITION", "Holatni bunday o'zgartirib bo'lmaydi"); const updated = await prisma.order.update({ where: { id: order.id }, data: { status, history: { create: { status, note: req.body.note } } }, include: { items: true, history: true } }); ok(res, updated); } catch (e) { next(e); } });

app.post("/api/admin/products", requireAuth("admin"), async (req, res, next) => { try { const input = productInputSchema.safeParse(req.body); if (!input.success) return fail(res, 400, "VALIDATION_ERROR", "Ma'lumotlar noto'g'ri"); const slugBase = slugify(input.data.titleUz) || "product"; const product = await prisma.product.create({ data: { ...input.data, isActive: false, slug: `${slugBase}-${crypto.randomUUID().slice(0, 8)}` }, include: productInclude }); ok(res, product, 201); } catch (e) { next(e); } });
app.patch("/api/admin/products/:id", requireAuth("admin"), async (req, res, next) => { try { const id = routeParam(req.params.id); const input = productInputSchema.safeParse(req.body); if (!input.success) return fail(res, 400, "VALIDATION_ERROR", "Ma'lumotlar noto'g'ri"); if (input.data.isActive) { const count = await prisma.productImage.count({ where: { productId: id } }); if (!count) return fail(res, 409, "PRODUCT_NEEDS_IMAGE", "Mahsulotni ko'rsatish uchun rasm kerak"); } const product = await prisma.product.update({ where: { id }, data: input.data, include: productInclude }); ok(res, product); } catch (e: any) { if (e.code === "P2025") return fail(res, 404, "NOT_FOUND", "Mahsulot topilmadi"); next(e); } });
app.delete("/api/admin/products/:id", requireAuth("admin"), async (req, res, next) => { try { await prisma.product.delete({ where: { id: routeParam(req.params.id) } }); ok(res, { deleted: true }); } catch (e) { next(e); } });
app.post("/api/admin/products/:id/images", requireAuth("admin"), upload.array("images", 6), async (req, res, next) => { try { const productId = routeParam(req.params.id); const files = req.files as Express.Multer.File[]; if (!files?.length) return fail(res, 415, "UNSUPPORTED_IMAGE", "Rasm tanlanmagan yoki formati noto'g'ri"); const existing = await prisma.productImage.count({ where: { productId } }); if (existing + files.length > 6) return fail(res, 409, "IMAGE_LIMIT", "Ko'pi bilan 6 rasm yuklash mumkin"); const directory = path.join(uploadRoot, productId); await fs.mkdir(directory, { recursive: true }); const created = []; for (let index = 0; index < files.length; index++) { const id = crypto.randomUUID(); const base = path.join(directory, id); await Promise.all([["sm", 480], ["md", 800], ["lg", 1400]].map(async ([name, width]) => sharp(files[index].buffer).rotate().resize({ width: width as number, withoutEnlargement: true }).webp({ quality: 84 }).toFile(`${base}-${name}.webp`))); created.push(await prisma.productImage.create({ data: { productId, sortOrder: existing + index, originalPath: `/uploads/${productId}/${id}-lg.webp`, smPath: `/uploads/${productId}/${id}-sm.webp`, mdPath: `/uploads/${productId}/${id}-md.webp`, lgPath: `/uploads/${productId}/${id}-lg.webp` } })); } ok(res, created, 201); } catch (e) { next(e); } });
app.delete("/api/admin/images/:id", requireAuth("admin"), async (req, res, next) => { try { await prisma.productImage.delete({ where: { id: routeParam(req.params.id) } }); ok(res, { deleted: true }); } catch (e) { next(e); } });
app.get("/api/admin/customers", requireAuth("admin"), async (req, res, next) => { try { const search = String(req.query.search ?? ""); ok(res, await prisma.customer.findMany({ where: search ? { OR: [{ phone: { contains: search } }, { name: { contains: search, mode: "insensitive" } }] } : {}, include: { _count: { select: { orders: true } } }, orderBy: { createdAt: "desc" } })); } catch (e) { next(e); } });

app.use((error: unknown, _req: Request, res: Response, _next: NextFunction) => {
  if (error instanceof ZodError) return fail(res, 400, "VALIDATION_ERROR", "Ma'lumotlar noto'g'ri", Object.fromEntries(error.issues.map(issue => [issue.path.join("."), issue.message])));
  if (error instanceof SyntaxError && "body" in error) return fail(res, 400, "VALIDATION_ERROR", "JSON formati noto'g'ri");
  if (error instanceof multer.MulterError) return fail(res, 413, "UNSUPPORTED_IMAGE", "Rasm hajmi yoki soni noto'g'ri");
  if (error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2025") return fail(res, 404, "NOT_FOUND", "Resurs topilmadi");
  console.error(error); return fail(res, 500, "INTERNAL", "Kutilmagan xatolik");
});
export default app;
